
# 应用标题
Title: "flare"
# 应用页脚
Footer: 由 <a href="https://github.com/soulteary/docker-flare">Flare</a> ❤️ 强力驱动
# 在新窗口中打开应用
OpenAppNewTab: true
# 在新窗口中打开书签
OpenBookmarkNewTab: true
# 展示顶部标题组件
ShowTitle: true
# 默认的首页问候语
Greetings: 你好
# 展示搜索组件
ShowSearchComponent: true
# 禁用搜索框自动获取焦点
DisabledSearchAutoFocus: false
# 展示日期组件
ShowDateTime: true
# 展示应用组件
ShowApps: true
# 展示书签组件
ShowBookmarks: true
# 隐藏界面中的设置按钮
HideSettingButton: false
# 隐藏界面中的帮助按钮
HideHelpButton: false
# 加密展示链接
EnableEncryptedLink: false
# 链接图标展示模式
IconMode: "DEFAULT"
# 应用主体
Theme: "blackboard"
# 是否启用天气组件
ShowWeather: true
# 天气组件使用的位置，仅在程序自动识别出错时，需要修改
Location: "北京市"
# 保持界面中链接大小写和配置中一致
KeepLetterCase: false
